export const FETCHING_PUBLIC_PROFILE = 'FETCHING_PUBLIC_PROFILE'
export const FETCHED_PUBLIC_PROFILE_SUCCESS = 'FETCHED_PUBLIC_PROFILE_SUCCESS'
export const FETCHED_PUBLIC_PROFILE_ERROR = 'FETCHED_PUBLIC_PROFILE_ERROR'

export const REQUESTED_PROFILE_UNLOCK = 'REQUESTED_PROFILE_UNLOCK'
export const PROFILE_UNLOCK_SUCCESS = 'PROFILE_UNLOCK_SUCCESS'
export const PROFILE_UNLOCK_FAILURE = 'PROFILE_UNLOCK_FAILURE'

export const REQUEST_EDIT_PROFILE = 'REQUEST_EDIT_PROFILE'
export const EDIT_FIELD = 'EDIT_FIELD'

export const UPLOADING_IMAGE = 'UPLOADING_IMAGE'
export const UPLOADED_IMAGE_SUCCESS = 'UPLOADED_IMAGE_SUCCESS'
export const UPLOADED_IMAGE_FAILURE = 'UPLOADED_IMAGE_FAILURE'

export const REQUESTED_PROFILE_SAVE = 'REQUESTED_PROFILE_SAVE'
export const REQUESTED_PROFILE_SAVE_SUCCESS = 'REQUESTED_PROFILE_SAVE_SUCCESS'
export const REQUESTED_PROFILE_SAVE_ERROR = 'REQUESTED_PROFILE_SAVE_ERROR'
export const REQUEST_PROFILE_CREATE = 'REQUEST_PROFILE_CREATE'
export const REQUEST_PROFILE_CREATE_SUCCESS = 'REQUEST_PROFILE_CREATE_SUCCESS'
export const REQUEST_PROFILE_CREATE_ERROR = 'REQUEST_PROFILE_CREATE_ERROR'
export const REQUESTED_PROFILE_OPEN = 'REQUESTED_PROFILE_OPEN'
export const REQUESTED_PROFILE_OPEN_SUCCESS = 'REQUESTED_PROFILE_OPEN_SUCCESS'
export const REQUESTED_PROFILE_OPEN_FAILURE = 'REQUESTED_PROFILE_OPEN_FAILURE'
export const REQUESTED_PROFILE_SYNC = 'REQUESTED_PROFILE_SYNC'
export const REQUESTED_PROFILE_SYNC_SUCCESS = 'REQUESTED_PROFILE_SYNC_SUCCESS'
export const REQUESTED_PROFILE_SYNC_FAILURE = 'REQUESTED_PROFILE_SYNC_FAILURE'

export const REQUESTED_PROFILE_ITEM_REMOVE = 'REQUESTED_PROFILE_ITEM_REMOVE'
export const REQUESTED_PROFILE_ITEM_REMOVE_SUCCESS =
  'REQUESTED_PROFILE_ITEM_REMOVE_SUCCESS'
export const REQUESTED_PROFILE_ITEM_REMOVE_ERROR =
  'REQUESTED_PROFILE_ITEM_REMOVE_ERROR'
export const REQUESTED_IMAGE_REMOVE = 'REQUESTED_IMAGE_REMOVE'
export const REQUESTED_IMAGE_REMOVE_SUCCESS = 'REQUESTED_IMAGE_REMOVE_SUCCESS'
export const REQUESTED_IMAGE_REMOVE_ERROR = 'REQUESTED_IMAGE_REMOVE_ERROR'
