#!/usr/bin/env node

const version = require('../package.json').version
const execute = require('child_process').execSync
const {
  DEFAULT_LOCAL_ENS_ADDRESS,
  DEFAULT_LOCAL_IPFS_GATEWAY,
} = require('./config/local')

execute('rimraf ./build', { stdio: 'inherit' })
execute(`copy-aragon-ui-assets -n aragon-ui ./build`, {
  stdio: 'inherit',
})

process.env.REACT_APP_PACKAGE_VERSION = version
process.env.REACT_APP_ETH_NETWORK_TYPE = 'local'
process.env.REACT_APP_ENS_REGISTRY_ADDRESS = DEFAULT_LOCAL_ENS_ADDRESS
process.env.REACT_APP_IPFS_GATEWAY = DEFAULT_LOCAL_IPFS_GATEWAY
process.env.REACT_APP_ASSET_BRIDGE = 'ipfs'

execute(
  `parcel build src/index.html --out-dir ./build --public-url ./ --no-cache`,
  { stdio: 'inherit' }
)
