#!/usr/bin/env node

const version = require('../package.json').version
const execute = require('child_process').execSync

execute('rimraf build/', { stdio: 'inherit' })
execute('npm run ui-assets', { stdio: 'inherit' })

process.env.REACT_APP_PACKAGE_VERSION = version
process.env.SENTRY_DSN =
  'https://eb128ce663d24c3caacc0331f61e9950@sentry.io/1500311'
execute(
  `parcel build src/index.html --out-dir ./build --public-url ./ --no-cache`,
  { stdio: 'inherit' }
)
