#!/usr/bin/env node

const execute = require('child_process').execSync

const clientPort = process.env.REACT_APP_PORT || 3000

execute(`npm run ui-assets && parcel serve src/index.html --port ${clientPort} --out-dir ./build --no-cache`, {
  stdio: 'inherit'
})
