#!/usr/bin/env node

const version = require('../package.json').version
const execute = require('child_process').execSync

const clientPort = process.env.REACT_APP_PORT || 3000

execute(`copy-aragon-ui-assets -n aragon-ui ./build`, {
  stdio: 'inherit',
})

process.env.REACT_APP_PACKAGE_VERSION = version
execute(
  `parcel serve src/index.html --port ${clientPort} --out-dir ./build --no-cache`,
  { stdio: 'inherit' }
)
