export const APP_MODE_HOME = Symbol('APP_MODE_HOME')
export const APP_MODE_ORG = Symbol('APP_MODE_ORG')
export const APP_MODE_SETUP = Symbol('APP_MODE_SETUP')
export const APP_MODE_INVALID = Symbol('APP_MODE_INVALID')

export const APPS_STATUS_ERROR = Symbol('APPS_STATUS_ERROR')
export const APPS_STATUS_READY = Symbol('APPS_STATUS_READY')
export const APPS_STATUS_LOADING = Symbol('APPS_STATUS_LOADING')
export const APPS_STATUS_UNLOADED = Symbol('APPS_STATUS_UNLOADED')

export const DAO_STATUS_ERROR = Symbol('DAO_STATUS_ERROR')
export const DAO_STATUS_READY = Symbol('DAO_STATUS_READY')
export const DAO_STATUS_LOADING = Symbol('DAO_STATUS_LOADING')
export const DAO_STATUS_UNLOADED = Symbol('DAO_STATUS_UNLOADED')

export const DAO_CREATION_STATUS_NONE = Symbol('DAO_CREATION_STATUS_NONE')
export const DAO_CREATION_STATUS_SUCCESS = Symbol('DAO_CREATION_STATUS_SUCCESS')
export const DAO_CREATION_STATUS_ERROR = Symbol('DAO_CREATION_STATUS_ERROR')
