name: Run tests

on: push
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install node
      uses: actions/setup-node@v1
      with:
        node-version: 14
    - name: Install dependencies
      # TODO remove --network-concurrency 1 once use-wallet 0.9.0 is published
      run: yarn install --frozen-lockfile --network-concurrency 1
    - name: Build Aragon
      run: yarn build
    - name: Run BundleWatch
      run: yarn bundlewatch
    - name: Run tests
      run: yarn test
    env:
      CI: true
      BUNDLEWATCH_GITHUB_TOKEN: ${{ secrets.BUNDLEWATCH_GITHUB_TOKEN }}
